### PR TITLE
Added 'noSort' option to disable sorting.

### PR DESCRIPTION
**Pull request by Kreozot**

### CODE REVIEW

**Comment by shannonmoeller** [comment]
lgtm. Merging. Will release when I'm back at a terminal.

Thanks for the PR! Sorry for the slow response.

**Comment by shannonmoeller** [comment]
I made a slight modification to this. I renamed the `noSort` option to `sort` with a default true value. So to disable sorting you pass `sort: false` now:

```js
columns(['foo', 'bar'], { sort: false });
```

Published as v1.1.0.

**Comment by Kreozot** [comment]
@shannonmoeller Draw you attention that you forgot to change this option in readme.md

**Comment by shannonmoeller** [comment]
Well that's just embarrassing. Thanks.

**Comment by shannonmoeller** [comment]
Fixed.

**Pull request merged**
